---
title: "GDV Etienne Roulet LO4"
output: html_notebook
---

```{r}
all_matches_10_Players_1980 <- all_matches %>%
  filter(complete.cases(.) & start_date > 1980) %>%
  group_by(player_name) %>%
  summarise(played = n()) %>%
  arrange(desc(played)) %>%
  slice(1:10) %>%
  ungroup()

all_matches_10best <- all_matches %>%
  filter(player_name %in% all_matches_10_Players_1980$player_name)

ggplot(all_matches_10best, aes(x=start_date, y=double_faults))+
  geom_col( aes ( colour = factor(double_faults))) +
  facet_wrap(~ player_name) +
  xlab("") +
  ylab("Anzahl Doppelfehler")+
  theme(legend.position="none") 
```
```{r}

all_matches_10_Players_1980 <- all_matches %>%
  filter(complete.cases(.) & start_date > 1980) %>%
  group_by(player_name) %>%
  summarise(played = n()) %>%
  arrange(desc(played)) %>%
  slice(1:10) %>%
  ungroup()

all_matches_10best <- all_matches %>%
  filter(player_name %in% all_matches_10_Players_1980$player_name)

summary(all_matches_10best)

```


```{r}
library(tidyverse)
all_matches_10_Players_1980 <- all_matches %>%
  filter(complete.cases(.) & start_date > 1980) %>%
  group_by(player_name) %>%
  summarise(played = n()) %>%
  arrange(desc(played)) %>%
  slice(1:10) %>%
  ungroup()

all_matches_10best <- all_matches %>%
  filter(player_name %in% all_matches_10_Players_1980$player_name)

print(all_matches_10best)

summarys <- all_matches_10best %>%
  group_by(player_name) %>%
  summarise(total_doppelfehler = sum(double_faults)) %>%
  ungroup()

ggplot(all_matches_10best, aes(y=double_faults))+
  geom_boxplot() +
  xlab("") +
  ylab("Anzahl Doppelfehler")+
  facet_wrap(~player_name)
```

```{r}
library(ggplot2)
library(tidyverse)

betting_won_loose <- betting_totals %>%
  inner_join(all_matches, by=c("team1" = "player_id", "team2" = "opponent_id" )) %>%
  sample_n(size=100) %>%
  arrange(book_id)  %>%
  group_by(book_name)

statistics <- all_matches %>%
  group_by(player_name) %>%
  summarise(double_faults = sum(double_faults), aces = sum(aces), times_played = n(), double_faults_per_play = double_faults / times_played, aces_per_play = aces / times_played) %>%
  ungroup()


player_stats <- statistics %>%
  sample_n(size=8)


ggplot(player_stats, aes(x=player_name, y=double_faults_per_play, fill=player_name)) +
  geom_col() +
  labs(title = "Anzahl der Doppelfehler", subtitle = "pro Spieler") +
  ylab("Doppelfehler pro Spieltag")

  
```



```{r}
library(ggplot2)
library(tidyverse)

betting_won_loose <- betting_totals %>%
  inner_join(all_matches, by=c("team1" = "player_id", "team2" = "opponent_id" )) %>%
  sample_n(size=100) %>%
  arrange(book_id)  %>%
  group_by(book_name)

statistics <- all_matches %>%
  group_by(player_name) %>%
  summarise(double_faults = sum(double_faults), aces = sum(aces), times_played = n(), double_faults_per_play = double_faults / times_played, aces_per_play = aces / times_played) %>%
  ungroup()


player_stats <- statistics %>%
  sample_n(size=8)


ggplot(player_stats, aes(x=player_name, y=double_faults_per_play, fill=player_name)) +
  geom_col() +
  labs(title = "Anzahl der Doppelfehler", subtitle = "pro Spieler") +
  ylab("Doppelfehler pro Spieltag")+
  xlab("Spielername")+
  scale_fill_discrete(name = "Spieler")+
  coord_polar(start = 0) 


  
  
```