---
title: "GDV Etienne Roulet LO2"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)

library(readr)


all_tournaments <- read_csv("all_tournaments.csv")
all_matches <- read_csv("all_matches.csv")
all_players <- read_csv("all_players.csv")

# Pie Chart from data frame with Appended Sample Sizes
result <- all_tournaments %>% 
          filter(year == 2017) %>% 
          arrange(desc(prize_money)) %>% 
          slice(1:10)
  

```

```{r}

library(treemap)

# Create data
group <- c(result['tournament'])
value <- c(result['prize_money'])
data <- data.frame(group,value)

print(data) 

# treemap
treemap(data,index = c("tournament","prize_money"),vSize = "prize_money")

```
```{r}

library(treemap)
library(tidyverse)
# Pie Chart from data frame with Appended Sample Sizes
result <- all_tournaments %>% 
          filter(year == 2017) %>% 
          arrange(desc(prize_money)) %>%
          slice(1:25)

# Create data
group <- c(result['tournament'] )
value <- c(result['prize_money'])
data <- data.frame(group,value)

print(data) 

# treemap
new_data <- data %>%
  mutate(prize_money = round(prize_money / 1000000, digits = 2)) %>%
  mutate(group.Index=paste(tournament, prize_money, sep ="\n"))

treemap(new_data,index = c("group.Index","prize_money"),vSize = "prize_money", title = "Preisgeld 2017 in Mio", bg.labels=c("transparent"),fontcolor.labels=c("white"),)

```

```{r}

library(treemap)
library(tidyverse)
# Pie Chart from data frame with Appended Sample Sizes
result <- all_tournaments %>% 
          filter(year == 2017) %>% 
          arrange(desc(prize_money)) %>% 
          slice(1:5)

slices <- c(result$prize_money)
lbls <- c(result$tournament)
pie(slices, labels = lbls, main="The biggest Tennis Tournaments")
```
```{r}
# Load ggplot2
library(ggplot2)

# Create data

result_of_court_types <- all_tournaments %>% 
          filter(year == 2017) %>% 
          arrange(desc(court_surface)) %>%
        group_by(court_surface) %>% 
        summarise(n = n()) %>%
        filter(!is.na(court_surface))
print(result_of_court_types)

data <- data.frame(
  court_types=result_of_court_types$court_surface,  
  Anzahl=result_of_court_types$n
  )

# Barplot
ggplot(data, aes(x=court_types, y=Anzahl, fill=court_types)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual("Legende", values = c("Carpet" = "green4", "Clay" = "tomato", "Grass" = "green", "Hard" = "royalblue3")) +
  labs(title="Tennis Untergründe 2017 ATP") +
  xlab("Spielunterlage") + ylab("Anzahl Spiele 2017")

```



```{r}
# Load ggplot2
library(ggplot2)

# Create data

result_of_court_types <- all_tournaments %>% 
          filter(year == 2017) %>% 
          arrange(desc(court_surface)) %>%
        group_by(court_surface) %>% 
        summarise(n = n()) %>%
        filter(!is.na(court_surface))
print(result_of_court_types)

data <- data.frame(
  court_types=result_of_court_types$court_surface,  
  Anzahl=result_of_court_types$n
  )



# Barplot
ggplot(data, aes(x=court_types, y=Anzahl, fill=court_types)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual("Legende", values = c("Carpet" = "green4", "Clay" = "tomato", "Grass" = "green", "Hard" = "royalblue3")) +
  labs(title="Tennis Untergründe 2017 ATP") +
  xlab("Spielunterlage") + ylab("Anzahl Spiele 2017")


```

```{r}
# Load ggplot2
library(ggplot2)

# Create data

result_of_court_types <- all_tournaments %>% 
          filter(year == 1950) %>% 
          arrange(desc(court_surface)) %>%
        group_by(court_surface) %>% 
        summarise(n = n())
print(result_of_court_types)

data <- data.frame(
  court_types=result_of_court_types$court_surface,  
  Anzahl=result_of_court_types$n
  )

# Barplot
ggplot(data, aes(x=court_types, y=Anzahl, fill=court_types)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual("Legende", values = c("Carpet" = "green4", "Clay" = "tomato", "Grass" = "green", "Hard" = "royalblue3")) +
  labs(title="Tennis Untergründe 1950 ATP") +
  xlab("Spielunterlage") + ylab("Anzahl Spiele 1950")

```

```{r}
print(all_matches)

result_of_winnings <- all_matches %>%
  filter(!is.na(player_name)) %>%
  group_by(player_name) %>%
  summarise(wins = n()) %>%
  arrange(desc(wins)) %>%
  slice(1:10) 


pie(result_of_winnings$wins, labels = result_of_winnings$player_name, main="Gewonnene ATP Titel seit 1950") + 
  scale_fill_manual(values = result_of_winnings$wins) +
  theme_void()



```

```{r}

result_of_winnings = result_of_winnings %>%
  arrange(desc(wins))



print(result_of_winnings)


ggplot(result_of_winnings, aes(x=player_name, y=wins, fill=wins)) + 
  geom_bar(stat = "identity") +
  labs(title="Top 10 Tennis Spieler als Barplot") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_x_discrete() +
  xlab("Spieler Name") + 
  ylab("Gewonnen ATP Titel")                 
```




```{r}
library("tidyverse")
library("ggplot2")

winnings <- all_matches %>%
  group_by(year) %>%
  summarise(prize_money = n()) %>%
  filter(year <= 2017)


ggplot(winnings, aes(x=year, y=prize_money)) +
  labs(title="Historische Preisgeld Änderung im ATP Tennis 1950 - 2017") +
  geom_line() +
  xlab("Jahr") +
  ylab("Preisgeld in $")

```

```{r}
library(ggparliament)
# install.packages("tidyverse")
library(tidyverse)

print(election_data)
# Data
UK <- election_data %>%
  filter(country == "UK" & year == 2017)

print(UK)
# Create the data frame to be used
uk_semicircle <- parliament_data(election_data = UK,
                                 type = "semicircle", # Parliament type
                                 parl_rows = 10,      # Number of rows of the parliament
                                 party_seats = UK$seats) # Seats per party

ggplot(uk_semicircle, aes(x = x, y = y, colour = party_short)) +
  geom_parliament_seats() + 
  theme_ggparliament() +
  labs(title = "Wahlen in UK, 2017", subtitle="Anzahl Sitzte: 650 Sitzte, Mehrheit ab 320", caption="Quelle: library(ggparliament)" ) +
  scale_colour_manual(values = uk_semicircle$colour, 
                      limits = uk_semicircle$party_short) +
  guides(color=guide_legend("Partei"))
```
```{r}
UK <- election_data %>%
  filter(country == "UK" & year == 2017)

ggplot(UK, aes(x = party_short, y = seats, fill =party_long)) +
  geom_col() + 
  labs(title = "Wahlen in UK, 2017", subtitle="Anzahl Sitzte: 650 Sitzte, Mehrheit ab 320", caption="Quelle: library(ggparliament)" ) +
  xlab("Anzahl Sitze") +
  ylab("Anzahl Sitze")+
  guides(color=guide_legend("Partei"))

```





